CREATE TABLE Users (
	Username TEXT PRIMARY KEY NOT NULL,
	Password TEXT NOT NULL
);

CREATE TABLE Sessions (
	SessionID TEXT NOT NULL,
	Username TEXT NOT NULL,
	PRIMARY KEY(SessionID, Username),
	CONSTRAINT UserSession
		FOREIGN KEY(Username)
		REFERENCES Users(Username)
		ON DELETE CASCADE
);

CREATE TABLE Tasks (
	TaskID INTEGER PRIMARY KEY AUTOINCREMENT,
	Description TEXT NOT NULL,
	CreatedTimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	DueDate DATE,
	DueTime TIME,
	TaskComplete INTEGER DEFAULT 0 NOT NULL,
	Username TEXT NOT NULL,
	CONSTRAINT UserTask
		FOREIGN KEY(Username)
		REFERENCES Users(Username)
		ON DELETE CASCADE
);

CREATE TABLE Tags (
	TagName TEXT NOT NULL,
	TaskID INTEGER NOT NULL,
	PRIMARY KEY(TagName, TaskID),
	CONSTRAINT TaskTag
		FOREIGN KEY(TaskID)
		REFERENCES Tasks(TaskID)
		ON DELETE CASCADE
);
