CREATE TABLE Tasks (
	TaskID INTEGER PRIMARY KEY AUTOINCREMENT,
	Description TEXT NOT NULL,
	CreatedTimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	DueTimeStamp TIMESTAMP,
	TaskComplete INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE Tags (
	TagName TEXT NOT NULL,
	TaskID INTEGER NOT NULL,
	PRIMARY KEY(TagName, TaskID),
	CONSTRAINT TaskTag
		FOREIGN KEY(TaskID)
		REFERENCES Tasks(TaskID) 
		ON DELETE CASCADE
);
